<!--// Left Menue 1 - BEGIN //-->
<TABLE BORDER="0" WIDTH="140" CELLSPACING="1" CELLPADDING="0" BGCOLOR="#000000">
 <TR>
  <TD WIDTH="140" HEIGHT="20" BGCOLOR="#000000" ALIGN="CENTER" VALIGN="MIDDLE" CLASS="menue">>CELL_TITLE<</TD>
 </TR>
 <TR>
  <TD BGCOLOR="#FFFFFF" WIDTH="140" ALIGN="CENTER" VALIGN="MIDDLE">>CELL_INDEX<</TD>
 </TR>
</TABLE>
<!--// Left Menue 1 - END //-->