<!--// CELL MAIN 1 - BEGIN //-->
<TABLE CELLSPACING="1" CELLPADDING="0" BGCOLOR="#000000" BORDER="0" WIDTH="688" class="content">
 <TR>
  <TD WIDTH="688" HEIGHT="20" BGCOLOR="#000000" ALIGN="CENTER" VALIGN="MIDDLE" CLASS="menue">>>CELL_TITLE<<</TD>
 </TR>
 <TR>
  <TD BGCOLOR="#FFFFFF" WIDTH="688" ALIGN="CENTER" VALIGN="MIDDLE" CLASS="NEWS"><BR>>>CELL_INDEX<<<BR><BR></TD>
 </TR>
</TABLE>
<!--// CELL MAIN 1 - END //-->