<!--// Search Menue - BEGIN //-->
<TABLE BORDER="0" WIDTH="140" CELLSPACING="1" CELLPADDING="0" BGCOLOR="#000000">
 <TR>
  <TD WIDTH="140" HEIGHT="20" BGCOLOR="#000000" ALIGN="CENTER" VALIGN="MIDDLE" CLASS="menue">Search Menu</TD>
 </TR>
 <TR>
  <TD BGCOLOR="#FFFFFF" WIDTH="140" ALIGN="CENTER" VALIGN="MIDDLE" CLASS="login"><FORM ACTION="index.php" METHOD="GET"><br><INPUT TYPE="HIDDEN" NAME="id" VALUE="search"><INPUT TYPE="TEXT" NAME="search" SIZE="10" MAXLENGTH="256" PLACEHOLDER="Search..."><br><br><INPUT TYPE="Submit" VALUE="Search"><br></FORM></TD>
 </TR>
</TABLE>
<!--// Search Menue - END //-->